/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'IEp:apple': typeof import('~icons/ep/apple')['default']
    'IEp:circlePlus': typeof import('~icons/ep/circle-plus')['default']
    IEpApple: typeof import('~icons/ep/apple')['default']
    IEpCirclePlus: typeof import('~icons/ep/circle-plus')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpHome: typeof import('~icons/ep/home')['default']
    IPngIconParkSolidBadminton: typeof import('~icons/png/icon-park-solid-badminton')['default']
    'ISvg:home': typeof import('~icons/svg/home')['default']
    'ISvg:iconParkSolidApple': typeof import('~icons/svg/icon-park-solid-apple')['default']
    ISvgHome: typeof import('~icons/svg/home')['default']
    'ISvgIconParkSolid-Apple': typeof import('~icons/svg/icon-park-solid--apple')['default']
    ISvgIconParkSolidApple: typeof import('~icons/svg/icon-park-solid-apple')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VxeColumn: typeof import('vxe-table/es/column')['default']
    VxeTable: typeof import('vxe-table/es/table')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
